const fs = require('fs');
const path = require('path');

const SRC_DIR = __dirname;
const DEFAULT_DIST_FILE = path.join(SRC_DIR, 'index.html');
const FORCE = process.argv.includes('--force');

function getOutputFile() {
  const outIndex = process.argv.indexOf('--out');
  if (outIndex !== -1 && process.argv.length > outIndex + 1) {
    const userPath = process.argv[outIndex + 1];
    return path.isAbsolute(userPath) ? userPath : path.join(SRC_DIR, userPath);
  }
  return DEFAULT_DIST_FILE;
}

const DIST_FILE = getOutputFile();
const HEADER_COMMENT = '<!-- GENERATED BY build.js - edit templates/ instead of index.html. -->\n';

// Ordered JavaScript files to inject at the end of body
const JS_FILES = [
  'js/state.js',
  'js/navigation.js',
  'js/auth.js',
  'js/projects.js',
  'js/frontmatter.js',
  'js/chapters.js',
  'js/plates.js',
  'js/graphs.js',
  'js/tables.js',
  'js/anx1.js',
  'js/anx2.js',
  'js/anx3.js',
  'js/anx4.js',
  'js/anx5.js',
  'js/anx6.js',
  'js/anx7.js',
  'js/signatures.js',
  'js/pdf.js',
  'js/main.js'
];

function compile() {
  console.log('Compiling DSR Portal...');
  try {
    // 1. Start with head
    let html = HEADER_COMMENT + fs.readFileSync(path.join(SRC_DIR, 'templates', 'head.html'), 'utf8');

    // 2. Append auth screen
    html += fs.readFileSync(path.join(SRC_DIR, 'templates', 'auth.html'), 'utf8');

    // 3. Append app shell (which contains placeholders for sidebar, topbar, and views)
    let shell = fs.readFileSync(path.join(SRC_DIR, 'templates', 'app-shell.html'), 'utf8');

    // Recursive helper to resolve placeholders like {{templates/sidebar.html}}
    const placeholderRegex = /\{\{([^}]+)\}\}/g;
    let match;
    while ((match = placeholderRegex.exec(shell)) !== null) {
      const templatePath = path.join(SRC_DIR, match[1]);
      if (fs.existsSync(templatePath)) {
        const content = fs.readFileSync(templatePath, 'utf8');
        shell = shell.replace(match[0], content);
        placeholderRegex.lastIndex = 0;
      } else {
        console.warn(`Warning: Template placeholder file not found: ${match[1]}`);
        shell = shell.replace(match[0], `<!-- Template ${match[1]} not found -->`);
      }
    }

    html += shell;

    // 4. Append modals & toast overlay
    html += fs.readFileSync(path.join(SRC_DIR, 'templates', 'modals.html'), 'utf8');

    // 5. Append JS Script tag references
    JS_FILES.forEach(file => {
      html += `\n<script src="${file}"></script>`;
    });

    // 6. Close body and html
    html += '\n</body>\n</html>';

    writeOutput(html);
  } catch (err) {
    console.error('Compilation Error:', err);
  }
}

function writeOutput(html) {
  if (fs.existsSync(DIST_FILE)) {
    const existing = fs.readFileSync(DIST_FILE, 'utf8');
    if (existing !== html && !FORCE) {
      const fallbackFile = path.join(SRC_DIR, path.basename(DIST_FILE, '.html') + '.built.html');
      fs.writeFileSync(fallbackFile, html, 'utf8');
      console.warn(`Warning: ${path.basename(DIST_FILE)} already exists and differs from the compiled templates.`);
      console.warn(`Preserved the current ${path.basename(DIST_FILE)}. Generated output is available in ${path.basename(fallbackFile)}.`);
      console.warn('If you want to overwrite the current file with the latest template compilation, rerun with --force.');
      return;
    }
  }

  fs.writeFileSync(DIST_FILE, html, 'utf8');
  console.log(`Successfully compiled DSR Portal into ${DIST_FILE}`);
}

function shouldWatch() {
  return process.argv.includes('--watch');
}

if (shouldWatch()) {
  compile();
  console.log('Watching templates/, js/ and css/ for changes...');
  
  const watchOptions = { recursive: true };
  
  const watcher = (eventType, filename) => {
    if (filename) {
      if (filename === 'index.html') return;
      console.log(`File change detected: ${filename}`);
      compile();
    }
  };

  fs.watch(path.join(SRC_DIR, 'templates'), watchOptions, watcher);
  fs.watch(path.join(SRC_DIR, 'js'), watchOptions, watcher);
  fs.watch(path.join(SRC_DIR, 'css'), watchOptions, watcher);
} else {
  compile();
}


